version: "3.4"

services:
  fug:
    image: fug
    build:
      context: .
      dockerfile: fug/Dockerfile
    ports:
      - 80:80
    depends_on: 
      - fug-api
  fug-api:
    image: fug-api
    build:
      context: .
      dockerfile: fug-api/Dockerfile
    ports:
      - 3000:3000
    environment:
      ADJECTIVES_PATH: src/data/english-adjectives.txt
      NOUNS_PATH: src/data/english-nouns.txt
      WEB_APP_URL: localhost
      WEB_API_URL: localhost/api
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
